spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: 6622Abc@123
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: finalcode